-- =============================================================
-- DEPRECATED — RLS policies are now managed in migrations
-- =============================================================
-- All Row-Level Security policies for TradeWise are defined in:
--   supabase/migrations/20260331_001_tradewise_initial_schema.sql  (base owner-scoped policies)
--   supabase/migrations/20260331_002_admin_auth_hardening.sql      (admin read/update policies)
--
-- Do NOT apply this file independently. Use:
--   supabase db reset      — fresh local setup
--   supabase db push       — apply to existing environment
-- =============================================================
