-- =============================================================
-- DEPRECATED — superseded by 20260331_001_tradewise_initial_schema.sql
-- =============================================================
-- This file previously contained an early-stage schema that has
-- been replaced by the canonical TradeWise schema migration.
-- Do NOT apply this file; it is kept for historical reference only.
-- All schema objects are now created by:
--   supabase/migrations/20260331_001_tradewise_initial_schema.sql
-- Admin hardening additions are in:
--   supabase/migrations/20260331_002_admin_auth_hardening.sql
-- =============================================================
